stages:
  - build
  - deploy

# Étape de build (création de l'image Docker)
build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn clean package -DskipTests
    - docker build -t $CI_REGISTRY_IMAGE .
  only:
    - main  # Vous pouvez changer cela pour une branche spécifique

# Étape de déploiement (transfert et exécution du conteneur Docker sur EC2)
deploy:
  stage: deploy
  image: docker:latest
  script:
    # Configurer Docker sur le runner
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Connexion SSH à l'instance EC2 et déploiement de l'image Docker
    - ssh -o StrictHostKeyChecking=no ec2-user@$EC2_IP << 'EOF'
      docker pull $CI_REGISTRY_IMAGE
      docker stop app1 || true
      docker rm app1 || true
      docker run -d -p 8081:8080 --name app1 $CI_REGISTRY_IMAGE
      EOF
  only:
    - main  # Vous pouvez changer cela pour une branche spécifique
