
spring.datasource.driver-class-name=org.postgresql.Driver


server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-ctopqci3esus73dc5an0-a.oregon-postgres.render.com/ydova_data_base

spring.datasource.username=ydova_data_base_user
spring.datasource.password=Vq6wz0pP1mLFlhKd2xrrlDVaRs0yIesX


spring.mvc.view.suffix= .html

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



logging.level.root=debug
